apiVersion: v1
kind: Pod
metadata:
  name: red
spec:
  initContainers:
    - name: init-sleep
      image: busybox:latest
      command: ["sh", "-c", "sleep 20"]
  containers:
    - name: redis-container
      image: redis
