apiVersion: v1
kind: Pod
metadata:
  name: webapp
spec:
  containers:
    - name: nginx-container
      image: nginx
      volumeMounts:
        - mountPath: /var/log/nginx
          name: log-volume
  volumes:
    - name: log-volume
      persistentVolumeClaim:
        claimName: claim-log-1
