apiVersion: v1
kind: Pod
metadata:
  name: yellow
spec:
  containers:
    - name: lemon
      image: busybox
      command: ["sh", "-c", "while true; do echo lemon; sleep 10; done"]
    - name: gold
      image: redis
