apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: elasticsearch
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: FluentD
  template:
    metadata:
      labels:
        app: FluentD
    spec:
      containers:
      - name: FluentD
        image: k8s.gcr.io/fluentd-elasticsearch:1.20
